services:

  db:
    image: mongo:3.5
    container_name: mongodb
    env_file:
      - src/main/resources/.env
      - ./.env
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: